### ISSUE TITLE
OR filters

### ISSUE THREAD

**Issue by jsocol** [erikrose/oedipus#13]
`OR` filters are _kind of_ supported in Sphinx. To add an `OR`, you need to set multiple values in the dict (c.f. the category filter in our search, which remains a `NoValidateMultipleChoiceField`). This is why `filter` dicts take tuples for the value.

Since support is only there for `OR`ing values of the _same_ field, I understand if you want to close this and not support it. But I thought I'd mention that the README is at least partially incorrect here.

E.g.:

``` python
vals = (1, 2, 3)
filters = []

# AND
for v in vals:
    filters.append({
        'filter': 'attrib',
        'value': (v,),  # Must be a tuple
    })

# OR
filters.append({
    'filter': 'attrib',
    'value': vals,  # Already a tuple
})

SphinxClient().query('foo', filters)
```

**Comment by erikrose** [comment]
Right, and oedipus does support ORs like that, just not the F syntax, because I didn't think it was worth the effort. While we're switching back and forth between ES and Sphinx, I thought we could just stick to the tuple/list syntax.

**Comment by jsocol** [comment]
It's probably worth at least updating this part of the README then:

```
No Or-ing of Filters

There's no way to "or" filters together in Sphinx, so oedipus
does not support elasticutils' F objects.
```
